# Generated by Django 4.0.6 on 2023-05-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niños', '0002_rename_niños_niños_tabla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niños_tabla2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('fechaDeNacimiento', models.DateField()),
                ('peso', models.IntegerField(max_length=100)),
                ('edad', models.IntegerField(max_length=100)),
                ('infoTalla', models.TextField(max_length=4000)),
            ],
        ),
    ]
