# Generated by Django 4.2.1 on 2023-05-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niños', '0003_niños_tabla2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niños_tabla2',
            name='infoTalla',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='niños_tabla2',
            name='nombre',
            field=models.TextField(max_length=40),
        ),
    ]
